#!/usr/bin/env bash
#see LICENSE for license

cd ../ && ln -s rocc-template rsa
#mv Makefrag Makefrag.old && ln -s rsa/config/Makefrag Makefrag
cd riscv-tools/riscv-isa-sim && ln -s ../../rsa/isa-sim/rsa rsa
mv configure.ac configure.ac.old && ln -s ../../rsa/isa-sim/configure.ac && ln -s ../../rsa/isa-sim/riscv-rsa.pc.in riscv-rsa.pc.in
#cd ../../src/main/scala && ln -s ../../../rsa/config/PrivateConfigs.scala PrivateConfigs.scala
